services:
  drone:
    image: drone/drone:2
    container_name: drone
    volumes:
      - /apps/data/drone:/data
    restart: unless-stopped
    networks:
      - homelab
    environment:
      DRONE_GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${RPC_SECRET}
      DRONE_USER_CREATE: username:itayvak,admin:true
      DRONE_SERVER_HOST: "ci.itayvak.com"
      DRONE_SERVER_PROTO: "https"
      DRONE_STARLARK_ENABLED: "true"

  drone_runner:
    image: drone/drone-runner-docker:1
    container_name: drone_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - homelab
    environment:
      DRONE_RPC_SECRET: ${RPC_SECRET}
      DRONE_RPC_HOST: "ci.itayvak.com"
      DRONE_RPC_PROTO: "https"

networks:
  homelab:
    external: true
