services:
  siyuan:
    image: b3log/siyuan:v3.8.0
    container_name: siyuan
    command: ['serve', '--workspace=/siyuan/workspace/', '--accessAuthCode=${ACCESS_CODE}']
    volumes:
      - /apps/data/siyuan:/siyuan/workspace
    restart: unless-stopped
    environment:
      # A list of time zone identifiers can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Asia/Tel_Aviv
    networks:
      - homelab

networks:
  homelab:
    external: true
