services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://monitoring.itayvak.com
    volumes:
      - /apps/data/beszel/beszel_data:/beszel_data
      - /apps/data/beszel/beszel_socket:/beszel_socket
    networks:
      - homelab

  beszel_agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel_agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /apps/data/beszel/beszel_agent_data:/var/lib/beszel-agent
      - /apps/data/beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/nvme0n1:/dev/nvme0n1
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://monitoring.itayvak.com
      TOKEN: ${TOKEN}
      KEY: ${KEY}
    cap_add:
      - SYS_RAWIO # required for S.M.A.R.T. data
      - SYS_ADMIN # required for NVMe S.M.A.R.T. data

networks:
  homelab:
    external: true
