services:
  mkdocs:
    build: 
      context: ..
      dockerfile: mkdocs/Dockerfile
    container_name: mkdocs
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
