site_name: Itayvak Homelab Docs
site_url: https://docs.itayvak.com
repo_url: https://github.com/itayvak/homelab

theme:
    name: material
    features:
    - navigation.indexes
    font:
        text: Google Sans
        code: Google Sans Code
    palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format

nav:
    - Home: index.md
    - Services: services.md
    - Filesystem: filesystem.md
    - Networking:
        - networking/index.md
        - Domain: networking/domain.md
        - Router: networking/router.md
        - Reverse proxy: networking/reverse-proxy.md
        - Remote access: networking/remote-access.md
    - Backups:
        - backups/index.md
        - Immich: backups/backups-immich.md
